apiVersion: apps/v1
kind: Deployment
metadata:
  name: imggen
  namespace: default
  labels:
    app: imggen
spec:
  replicas: 3
  selector:
    matchLabels:
      app: imggen
  template:
    metadata:
      labels:
        app: imggen
    spec:
      containers:
        - name: api
          image: imggen:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: api
          resources:
            requests:
              cpu: 0.25
              memory: 128Mi
            limits:
              cpu: 1
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: imggen
  namespace: default
  labels:
    app: imggen
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: api
  selector:
    app: imggen